With your application, please include the following coding samples using the data from https://github.com/CSSEGISandData/COVID-19:

1. Python: Download a timeseries of daily deaths per country

2. Python: Convert the table so that each country and each day is a separate row 

3.  Python: Provide code to upload the table from step 3 into an SQL table named deaths_total

4.  Python: From the data in step 2, calculate the daily change in deaths for each country

5.  Python: Provide code to upload the table from step 4 into an SQL table named deaths_change_python

6. SQL: Provide SQL code to calculate the daily change for each country using only the data from deaths_total and save it into an SQL table named deaths_change_sql

In [126]:
from __future__ import print_function
import pandas as pd
import pymysql
# from sqlalchemy import create_engine
from datetime import date, datetime, timedelta

user='root'
password='Phatxitho!304'
host='localhost'
database='covid19'

In [110]:
# download a timeseries of daily deaths per country
us_case = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"
us_death = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"

glob_cases = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
glob_death = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
glob_recov = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

cases = pd.read_csv(glob_cases)
deaths = pd.read_csv(glob_death)
recov = pd.read_csv(glob_recov)

In [111]:
# convert the table to appropriate format
def convert_df(df):
    df = df.drop(['Long', 'Lat'], axis=1)
    df = df.melt(id_vars=['Province/State', 'Country/Region'], var_name='date', value_name='total')
    df.date = pd.to_datetime(df.date)
    df['Province/State'].fillna('all', inplace=True)
    df.total.fillna(0, inplace=True)
    df.columns = ['prov_state','country_region','date','total']
    
    return df

In [113]:
# convert the table so that each country and each day is a separate row
cases = convert_df(cases)
deaths = convert_df(deaths)
recov = convert_df(recov)

newDeath = deaths.drop(['prov_state'], axis=1)
dates = deaths['date'].dt.floor('D')
dates = deaths['date'].dt.date
newDeath = newDeath.groupby(['country_region', dates]).sum().reset_index()
# newDeath

      country_region        date  total
0        Afghanistan  2020-01-22      0
1        Afghanistan  2020-01-23      0
2        Afghanistan  2020-01-24      0
3        Afghanistan  2020-01-25      0
4        Afghanistan  2020-01-26      0
...              ...         ...    ...
13027       Zimbabwe  2020-03-29      1
13028       Zimbabwe  2020-03-30      1
13029       Zimbabwe  2020-03-31      1
13030       Zimbabwe  2020-04-01      1
13031       Zimbabwe  2020-04-02      1

[13032 rows x 3 columns]

In [36]:
# newDeath.date[0].to_datetime()
# datetime(newDeath.date[0].strftime("%d-%m-%Y"))
# newDeath.date[0].strftime("%d-%m-%Y")

# deaths.sort_values(['total'], ascending=False)
# newDeath[newDeath['country_region']=='Australia']

In [90]:
# first approach
# sqlEngine = create_engine('mysql+pymysql://root:Phatxitho!304@localhost/covid19', pool_recycle=3600)
# conn = sqlEngine.connect()

# second approach
# conn = pymysql.connect(user=user,password=password, host=host, database=database)
# cursor= conn.cursor()
# conn.close()

In [131]:
# query to create deaths_total tabla
create_death_tot = "CREATE TABLE IF NOT EXISTS `deaths_total` (`country_region` varchar(16) NOT NULL, `date` date NOT NULL, `total` int(11) NOT NULL, PRIMARY KEY (`country_region`, `date`))"
                    
# insert query
insert_deathTotal = "INSERT IGNORE INTO `deaths_total` (`country_region`, `date`, `total`) VALUES (%s, %s, %s)"

# select deaths_total
select_deathTotal = "SELECT * FROM `deaths_total`"

In [124]:
conn = pymysql.connect(user=user,password=password, host=host, database=database)

try:
    cursor = conn.cursor()
    
    # create deaths_total table
    cursor.execute(create_death_tot)
    
    for i, row in newDeath.iterrows():
        cursor.execute(insert_deathTotal, (row[0], row[1].strftime("%Y-%m-%d"), int(row[2])))
        conn.commit()
finally:
    conn.close()

C:\Users\phath\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\pymysql\cursors.py:170: Warning: (1050, "Table 'deaths_total' already exists")
  result = self._query(query)
C:\Users\phath\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\pymysql\cursors.py:170: Warning: (1265, "Data truncated for column 'country_region' at row 1")
  result = self._query(query)

In [132]:
conn = pymysql.connect(user=user,password=password, host=host, database=database)

try:
    cursor = conn.cursor()
    # select 
    cursor.execute(select_deathTotal)
    data = cursor.fetchall()
finally:
    conn.close()

In [30]:
# sqlalchemy approach
try:
    frame = newDeath.to_sql(name='deaths_total', con=conn, if_exists='fail', schema='covid19');
except ValueError as vx:
    print(vx)
except Exception as ex:   
    print(ex)
else:
    print("Table %s created successfully."%tableName);   
finally:
    conn.close()

Execution failed on sql 'SELECT name FROM sqlite_master WHERE type='table' AND name=?;': not all arguments converted during string formatting

In [69]:
config = {
  'user': 'root',
  'password': 'Phatxitho!304',
  'host': 'localhost',
    'port':'3306',
  'database': 'covid19',
  'raise_on_warnings': True
}

cnx = mysql.connector.connect(**config)
cursor = cnx.cursor()

DB_NAME = 'covid19'

TABLES = {}
TABLES['deaths_total'] = (
    "CREATE TABLE `deaths_total` IF NOT EXIST"
    "  `country_region` varchar(16) NOT NULL,"
    "  `date` date NOT NULL,"
    "  `total` int(11) NOT NULL,"
    "  PRIMARY KEY (`country_region`,`date`)"
    ") ENGINE=InnoDB"
)

for table_name in TABLES:
    table_description = TABLES[table_name]
    try:
        print("Creating table {}: ".format(table_name), end='')
        cursor.execute(table_description)
    except mysql.connector.Error as err:
        if err.errno == errorcode.ER_TABLE_EXISTS_ERROR:
            print("already exists.")
        else:
            print(err.msg)
    else:
        print("OK")

cursor.close()
cnx.close()

Creating table deaths_total: OK